### ISSUE TITLE
Installation does not install OpenBabel.

### ISSUE THREAD

**Issue by paulsaxe** [molssi-seamm/seamm#115]
* MolSSI Workflow version:
* Python version:
* Operating System:

### Description

Starting the JobServer, SEAMM errors because OpenBabel is not installed.

### What I Did

```
Please install openbabel using conda:
     conda install -c conda-forge openbabel
Traceback (most recent call last):
  File "/home/psaxe/miniconda3/envs/seamm/bin/jobserver", line 5, in <module>
    from seamm_jobserver.run_jobserver import run
  File "/home/psaxe/miniconda3/envs/seamm/lib/python3.10/site-packages/seamm_jobserver/__init__.py", line 11, in <module>
    from seamm_jobserver.jobserver import JobServer  # noqa: F401
  File "/home/psaxe/miniconda3/envs/seamm/lib/python3.10/site-packages/seamm_jobserver/jobserver.py", line 15, in <module>
    from seamm import run_flowchart
  File "/home/psaxe/miniconda3/envs/seamm/lib/python3.10/site-packages/seamm/__init__.py", line 23, in <module>
    from seamm.exec_flowchart import ExecFlowchart  # noqa: F401
  File "/home/psaxe/miniconda3/envs/seamm/lib/python3.10/site-packages/seamm/exec_flowchart.py", line 21, in <module>
    from molsystem import SystemDB
  File "/home/psaxe/miniconda3/envs/seamm/lib/python3.10/site-packages/molsystem/__init__.py", line 12, in <module>
    from molsystem.system_db import SystemDB  # noqa: F401
  File "/home/psaxe/miniconda3/envs/seamm/lib/python3.10/site-packages/molsystem/system_db.py", line 12, in <module>
    from .configuration import _Configuration
  File "/home/psaxe/miniconda3/envs/seamm/lib/python3.10/site-packages/molsystem/configuration.py", line 14, in <module>
    from .openbabel import OpenBabelMixin
  File "/home/psaxe/miniconda3/envs/seamm/lib/python3.10/site-packages/molsystem/openbabel.py", line 8, in <module>
    from openbabel import openbabel
ModuleNotFoundError: No module named 'openbabel'
```

**Comment by paulsaxe** [comment]
Nor `rdkit`: 
```(seamm) psaxe@molssi10:~$ jobserver
Please install rdkit using conda:
     conda install -c conda-forge rdkit
Traceback (most recent call last):
  File "/home/psaxe/miniconda3/envs/seamm/bin/jobserver", line 5, in <module>
    from seamm_jobserver.run_jobserver import run
  File "/home/psaxe/miniconda3/envs/seamm/lib/python3.10/site-packages/seamm_jobserver/__init__.py", line 11, in <module>
    from seamm_jobserver.jobserver import JobServer  # noqa: F401
  File "/home/psaxe/miniconda3/envs/seamm/lib/python3.10/site-packages/seamm_jobserver/jobserver.py", line 15, in <module>
    from seamm import run_flowchart
  File "/home/psaxe/miniconda3/envs/seamm/lib/python3.10/site-packages/seamm/__init__.py", line 23, in <module>
    from seamm.exec_flowchart import ExecFlowchart  # noqa: F401
  File "/home/psaxe/miniconda3/envs/seamm/lib/python3.10/site-packages/seamm/exec_flowchart.py", line 21, in <module>
    from molsystem import SystemDB
  File "/home/psaxe/miniconda3/envs/seamm/lib/python3.10/site-packages/molsystem/__init__.py", line 12, in <module>
    from molsystem.system_db import SystemDB  # noqa: F401
  File "/home/psaxe/miniconda3/envs/seamm/lib/python3.10/site-packages/molsystem/system_db.py", line 12, in <module>
    from .configuration import _Configuration
  File "/home/psaxe/miniconda3/envs/seamm/lib/python3.10/site-packages/molsystem/configuration.py", line 15, in <module>
    from .rdkit_ import RDKitMixin
  File "/home/psaxe/miniconda3/envs/seamm/lib/python3.10/site-packages/molsystem/rdkit_.py", line 8, in <module>
    from rdkit import Chem
ModuleNotFoundError: No module named 'rdkit'
(seamm) psaxe@molssi10:~$ conda install -c conda-forge rdkit
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.

ResolvePackageNotFound: 
  - python=3.1
```
